blog/urls.py
from django.urls import path
from .views import IndexView


app_name = 'blog'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User


# 文章分类
class Category(models.Model):
    name = models.CharField(max_length=20, verbose_name='分类')
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name
        ordering = ['id']

    def __str__(self):
        return self.name


# 文章标签
class Tag(models.Model):
    name = models.CharField(max_length=20, verbose_name='标签')
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name
        ordering = ['id']

    def __str__(self):
        return self.name


# 文章
class Article(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='作者')
    title = models.CharField(max_length=100, verbose_name='标题')
    content = models.TextField(verbose_name='内容')
    view = models.IntegerField(default=0, verbose_name='阅读量')
    is_top = models.BooleanField(default=False, verbose_name='置顶')
    slug = models.SlugField(unique=True)
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    update_date = models.DateTimeField(auto_now=True, verbose_name='修改时间')

    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='分类')
    tag = models.ManyToManyField(Tag, verbose_name='标签')

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-create_date']

    def __str__(self):
        return self.title[:20]


# 友情链接
class FriendLink(models.Model):
    name = models.CharField(max_length=50, verbose_name='网站名称')
    description = models.CharField(max_length=100, verbose_name='网站描述')
    logo = models.URLField(blank=True, verbose_name='网站LOGO')
    link = models.URLField(verbose_name='网站地址')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    is_show = models.BooleanField(default=False, verbose_name='显示')
    is_active = models.BooleanField(default=True, verbose_name='有效')

    class Meta:
        verbose_name = '友链'
        verbose_name_plural = verbose_name
        ordering = ['-create_date']

    def __str__(self):
        return self.name

blog/views.py
from django.shortcuts import render
from django.views import generic
from .models import Category, Tag, Article, FriendLink


class IndexView(generic.ListView):
    model = Article
    template_name = 'blog/index.html'




class Detail(generic.DetailView):
    pass

blog/templates/blog/base.html
<!doctype html>
<html lang="zh-CN">
<head>
  <!-- 必须的 meta 标签 -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap 的 CSS 文件 -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

  <title>Hello, world!</title>
</head>
<body>
<main>{% block content %}{% endblock %}</main>

<!-- jQuery 和 Bootstrap 集成包（集成了 Popper） -->
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-LCPyFKQyML7mqtS+4XytolfqyqSlcbB3bvDuH9vX2sdQMxRonb/M3b9EmhCNNNrV"
        crossorigin="anonymous"></script>

</body>
</html>

blog/templates/blog/base_right.html
{% load blog_tags static %}
<div class="card">
  <div class="card-header">
    <strong>文章分类</strong>
  </div>
  <ul class="list-group list-group-flush">
    {% get_category_list as category_list %}
    {% for category in category_list %}
      <li class="list-group-item">{{ category.name }}</li>
    {% endfor %}
  </ul>
</div>

<div class="card">
  <div class="card-header">
    <strong>标签云</strong>
  </div>
  <div class="card-body">
    {% get_tag_list as tag_list %}
    {% for tag in tag_list %}
      <div class="float-left">
        {{ tag.name }}
      </div>
    {% endfor %}
  </div>
</div>

<div class="card">
  <div class="card-header">
    <strong>友情链接</strong>
  </div>
  <div class="card-body">
    {% get_friend_link_list as friend_link_list %}
    {% for friend_link in friend_link_list %}
      <div class="float-left w-50 text-center">
        <a href="">{{ friend_link.name }}</a>
      </div>
    {% endfor %}
  </div>
</div>

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        此处为左侧区域
      </div>
      <div class="col-lg-4">
        {% include 'blog/base_right.html' %}
      </div>
    </div>
  </div>

{% endblock %}